Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,26 +1,29 @@
-name: Execution flow
+name: Execution Flow with PR
+
 on:
   push:
-  
+    branches: [ main ]
+  pull_request:
+    branches: [ main ]
+
 jobs:
   build:
-   runs-on: ubuntu-latest
-   steps:
-   - name: build job
-     run: echo "building the application"
-   
-     
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo " Building the application"
+
   test:
-   runs-on: ubuntu-latest
-   needs: build
-   steps:
-   - name: test job
-     run: echo "testing  the application"
-     
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - run: |
+          echo " Running tests"
+          exit 1   # Force fail for demo (remove this in real workflow)
+
   deploy:
-   runs-on: ubuntu-latest
-   needs: test
-   if: ${{success()}} 
-   steps:
-   - name: deploy job
-     run: echo "deploy the application"
+    runs-on: ubuntu-latest
+    needs: test
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
+    steps:
+      - run: echo " Deploying to Production (only on push to main and if tests passed)"      
+
